<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Category'                                   => 'Категория',
    'ID'                                         => '',
    'Structure'                                  => 'Структура',
    'Tree ID'                                    => '',
    'Article Group ID'                           => 'Код группы',
    'Child Article Group ID'                     => 'Код подгруппы',
    'Create Group'                               => 'Создать группу',
    'Description'                                => 'Описание',
    'Groups'                                     => 'Группы',
    'Parent Article Group ID'                    => '',
    'Alias'                                      => 'Псевдоним',
    'Anons'                                      => 'Анонс',
    'Are you sure you want to delete this item?' => 'Вы уверенны, что хотите удалить?',
    'Articles'                                   => 'Статьи',
    'Body'                                       => 'Основной текст статьи',
    'Create'                                     => 'Создать',
    'Create Tag'                                 => 'Создать тэг',
    'Create Article'                             => 'Создать статью',
    'Created At'                                 => 'Время создания',
    'Delete'                                     => 'Удалить',
    'Reset'                                      => 'Сбросить',
    'Search'                                     => 'Поиск',
    'Template'                                   => 'Шаблон',
    'Title'                                      => 'Название',
    'Tree ID'                                    => 'Категория',
    'Update'                                     => 'Обновить',
    'Update {modelClass}: '                      => 'Обновить {modelClass}:',
    'Updated At'                                 => 'Время обновления',
    'Used'                                       => 'Показывать',
    'Meta Tag'                                   => 'Метатэг',
    'Save'                                       => 'Сохранить',
];
