<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Вы уверенны, что хотите удалить?',
    'Article Group ID' => '',
    'Articles' => 'Статьи',
    'Child Article Group ID' => '',
    'Create' => 'Создать',
    'Create Article' => 'Создать статью',
    'Create Group' => 'Создать группу',
    'Delete' => 'Удалить',
    'Groups' => 'Группы',
    'ID' => '',
    'Parent Article Group ID' => '',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}:',
    'Alias' => 'Псевдоним',
    'Anons' => 'Анонс',
    'Body' => 'Основной текст статьи',
    'Created At' => 'Время создания',
    'Description' => 'Описание',
    'Title' => 'Название',
    'Updated At' => 'Время обновления',
    'Used' => 'Показывать',
];
